mindmap
  root((Apprenant))
    Dit
       Je veux partager des ressources utiles avec d'autres.
    Fait
       Partage des ressources utiles avec d'autres apprenants.
    Voit
       D'autres apprenants partagent des ressources.
       Confusion sur quelles ressources sont valides.
    Besoin
       Ressources claires et fiables.
       Validation des ressources partagées par le formateur.
   