@startuml

left to right direction
actor User as user
actor Admin as admin

rectangle "Blog System" {
    usecase "View All Articles" as UC_ViewArticles
    usecase "View Single Article" as UC_ViewArticle
    usecase "Add comments" as UC_AddComments
    usecase "View comments" as UC_ViewComments

    usecase "Crud articles" as UC_CrudArticles
    usecase "Crud categories" as UC_CrudCategories
    usecase "Crud tags" as UC_CrudTags
    usecase "Crud comments" as UC_CrudComments

}


user -- UC_ViewArticle
user -- UC_ViewArticles
user -- UC_AddComments
user -- UC_ViewComments

admin -- UC_CrudArticles
admin -- UC_CrudCategories
admin -- UC_CrudTags
admin -- UC_CrudComments


@enduml
