@startuml
left to right direction
skinparam packageStyle rectangle

' Define actors
actor "Formateur & Admin" as FA
actor Apprenant          as U

' Define use cases grouped in a package
package " " {
  usecase "Upload Document & Resource"    as UC_Upload
  usecase "Download Document & Resource"  as UC_Download
  usecase "Validate Document & Resource"  as UC_Validate
  usecase "Create Category"               as UC_Create
}

package "User Management" {
  usecase "Manage Users"                  as UC_ManageUsers
}

' Formateur & Admin permissions
FA --> UC_Upload
FA --> UC_Download
FA --> UC_Validate
FA --> UC_Create
FA --> UC_ManageUsers

' Apprenant permissions
U  --> UC_Upload
U  --> UC_Download
@enduml
