@startuml
left to right direction

actor Apprenant as U

package " " {
  usecase "Uploader un document & Ressource"    as UC_Upload
  usecase "Télécharger un document & Ressource" as UC_Download
}

U --> UC_Upload : uploads
U --> UC_Download : downloads
@enduml
