@startuml
title Partage de documents et de ressources - Cas d'Utilisation Général
left to right direction
actor Utilisateur as U
actor Formateur as F

rectangle "Actions" {
    usecase UC1 as "Télécharger un document"
    usecase UC2 as "Partager un document"
    usecase UC3 as "Consulter les ressources partagées"
    usecase UC4 as "Organiser les ressources"
    usecase UC6 as "Valider ou refuser un document"
}

U -- UC1 : "Télécharge"
U -- UC2 : "Partage"
U -- UC3 : "Consulte"
F -- UC4 : "Organise"
F -- UC6 : "Valide ou refuse"
@enduml
 