
@startuml
title Partage de documents et de ressources - Cas d'Utilisation - Sprint 2
left to right direction

actor Utilisateur as U
actor Formateur as F

rectangle "Sprint 2" {
    usecase UC3 as "Partager un document"
    usecase UC4 as "Organiser les ressources"
    usecase UC6 as "Valider ou refuser un document"
}

U -- UC3 : "Partage"
F -- UC4 : "Organise"
F -- UC6 : "Valide ou refuse"
@enduml
